import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service — Home Notes by Home Sales Ready',
  description: 'Terms of Service for Home Notes, the AI-powered property area intelligence tool by Home Sales Ready.',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 shadow-sm">
        <div className="max-w-4xl mx-auto px-4 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 font-black text-slate-900 text-lg tracking-tight hover:opacity-80 transition-opacity">
            <div className="bg-blue-600 p-1.5 rounded-lg">
              <svg className="text-white w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
              </svg>
            </div>
            Home<span className="text-blue-600">Notes</span>
          </Link>
          <Link href="/" className="text-sm font-bold text-blue-600 hover:underline">← Back to Home Notes</Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-12">
        <div className="bg-white rounded-3xl shadow-sm border border-slate-100 p-8 md:p-12">
          <h1 className="text-3xl font-black text-slate-900 mb-2">Terms of Service</h1>
          <p className="text-slate-500 text-sm mb-8">Last updated: 28 April 2026</p>

          <div className="prose prose-slate max-w-none space-y-8 text-slate-700 leading-relaxed">

            <section>
              <h2 className="text-xl font-black text-slate-900 mb-3">1. About Home Notes</h2>
              <p>Home Notes is an AI-powered property area intelligence tool operated by <strong>Kadima Systems Ltd</strong>, trading as <strong>Home Sales Ready</strong> ("we", "us", "our"), registered in England and Wales. By accessing or using Home Notes, you agree to be bound by these Terms of Service.</p>
              <p className="mt-2">If you do not agree to these terms, please do not use Home Notes.</p>
            </section>

            <section>
              <h2 className="text-xl font-black text-slate-900 mb-3">2. The Service</h2>
              <p>Home Notes provides AI-generated property area reports for addresses in England. Reports cover areas including (but not limited to): broadband speeds, nearby schools and their Ofsted ratings, crime statistics, flood risk, transport links, healthcare facilities, and local amenities.</p>
              <p className="mt-2">The service is provided free of charge to registered users. We reserve the right to introduce paid tiers or modify the service at any time with reasonable notice.</p>
            </section>

            <section>
              <h2 className="text-xl font-black text-slate-900 mb-3">3. AI-Generated Content — Important Disclaimer</h2>
              <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5 my-4">
                <p className="font-bold text-amber-900 mb-2">⚠️ Please read this section carefully.</p>
                <p className="text-amber-800">All reports generated by Home Notes are produced by an artificial intelligence (AI) language model. The information is based on the AI model's training data and <strong>may not reflect current, accurate, or real-world conditions</strong>.</p>
              </div>
              <p>Specifically, you acknowledge that:</p>
              <ul className="mt-3 space-y-2 list-disc pl-5">
                <li>Report data (including broadband speeds, school ratings, crime statistics, flood risk assessments, and local amenity information) is <strong>AI-generated and not sourced from live databases</strong>.</li>
                <li>The AI may produce information that is outdated, incomplete, or inaccurate.</li>
                <li>Reports should be treated as a general starting point for research only, <strong>not as professional, legal, financial, or surveying advice</strong>.</li>
                <li>Before making any property-related decision (buying, renting, or investing), you should always verify information independently from official sources including Ofsted, the Environment Agency, Ofcom, the ONS, and Land Registry.</li>
                <li>You should consult qualified professionals including surveyors, solicitors, and financial advisers before committing to any property transaction.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-black text-slate-900 mb-3">4. Limitation of Liability</h2>
              <p>To the fullest extent permitted by law:</p>
              <ul className="mt-3 space-y-2 list-disc pl-5">
                <li>Kadima Systems Ltd accepts <strong>no liability</strong> for any loss, damage, or harm arising from your use of or reliance on information provided by Home Notes.</li>
                <li>We are not responsible for any property decisions, financial commitments, or actions taken based on AI-generated reports.</li>
                <li>The service is provided "as is" without any warranty, express or implied, including warranties of accuracy, fitness for purpose, or merchantability.</li>
                <li>Our total liability to you for any claim shall not exceed the amount you have paid us in the 12 months preceding the claim (which, for free users, is £0).</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-black text-slate-900 mb-3">5. Your Account</h2>
              <p>To access full reports and save your search history, you must create an account with a verified email address. You are responsible for:</p>
              <ul className="mt-3 space-y-2 list-disc pl-5">
                <li>Maintaining the confidentiality of your password.</li>
                <li>All activity that occurs under your account.</li>
                <li>Ensuring the email address associated with your account is accurate and accessible.</li>
              </ul>
              <p className="mt-2">We reserve the right to suspend or terminate accounts that are used in violation of these terms.</p>
            </section>

            <section>
              <h2 className="text-xl font-black text-slate-900 mb-3">6. Acceptable Use</h2>
              <p>You agree not to use Home Notes to:</p>
              <ul className="mt-3 space-y-2 list-disc pl-5">
                <li>Scrape, harvest, or systematically extract data from the service.</li>
                <li>Resell or commercially exploit reports without our written permission.</li>
                <li>Attempt to circumvent any security or access controls.</li>
                <li>Use the service for any unlawful purpose.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-black text-slate-900 mb-3">7. Intellectual Property</h2>
              <p>The Home Notes platform, including its design, code, and branding, is owned by Kadima Systems Ltd. AI-generated reports are provided for your personal, non-commercial use. You may not reproduce, distribute, or publish report content without our permission.</p>
            </section>

            <section>
              <h2 className="text-xl font-black text-slate-900 mb-3">8. Privacy</h2>
              <p>Your use of Home Notes is also governed by our <Link href="/privacy" className="text-blue-600 hover:underline">Privacy Policy</Link>, which is incorporated into these terms by reference.</p>
            </section>

            <section>
              <h2 className="text-xl font-black text-slate-900 mb-3">9. Changes to These Terms</h2>
              <p>We may update these Terms of Service at any time. We will notify registered users of material changes by email. Continued use of the service after changes take effect constitutes your acceptance of the updated terms.</p>
            </section>

            <section>
              <h2 className="text-xl font-black text-slate-900 mb-3">10. Governing Law</h2>
              <p>These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
            </section>

            <section>
              <h2 className="text-xl font-black text-slate-900 mb-3">11. Contact</h2>
              <p>For any questions about these terms, please contact us:</p>
              <ul className="mt-2 space-y-1 list-none pl-0">
                <li><strong>Website:</strong> <a href="https://homesalesready.com" className="text-blue-600 hover:underline">homesalesready.com</a></li>
                <li><strong>WhatsApp:</strong> <a href="https://wa.me/447724601320" className="text-blue-600 hover:underline">07724 601320</a></li>
              </ul>
            </section>

          </div>
        </div>
      </main>

      <footer className="py-8 text-center text-xs text-slate-400">
        © 2026 Kadima Systems Ltd · <Link href="/" className="hover:text-slate-600">Home Notes</Link> · <a href="https://homesalesready.com" className="hover:text-slate-600">Home Sales Ready</a>
      </footer>
    </div>
  );
}
